# Generated by Django 4.2.7 on 2026-02-17 10:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('model_path', models.FileField(upload_to='models/')),
                ('version', models.CharField(max_length=50)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('precision', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('recall', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('f1_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('input_size', models.CharField(default='224x224', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_label', models.CharField(choices=[('NORMAL', 'Normal'), ('PNEUMONIA', 'Pneumonia')], max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High Confidence (>95%)'), ('MODERATE', 'Moderate Confidence (80-95%)'), ('LOW', 'Low Confidence (<80%)')], max_length=20)),
                ('processing_time', models.DecimalField(decimal_places=3, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_predictions', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Prediction Result',
                'verbose_name_plural': 'Prediction Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, unique=True)),
                ('config_value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='XRayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_path', models.ImageField(upload_to='xray_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('file_size', models.IntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(choices=[('JPEG', 'JPEG'), ('PNG', 'PNG')], max_length=10)),
                ('is_preprocessed', models.BooleanField(default=False)),
                ('preprocessing_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xray_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'X-Ray Image',
                'verbose_name_plural': 'X-Ray Images',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('UPLOAD', 'Image Upload'), ('ANALYZE', 'Image Analysis'), ('VIEW_RESULT', 'View Result'), ('DELETE_RESULT', 'Delete Result'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('additional_data', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_service.xrayimage')),
                ('prediction_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_service.predictionresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User History',
                'verbose_name_plural': 'User History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('execution_time', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='model_service.xrayimage')),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='model_service.xrayimage'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='model_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_service.modelversion'),
        ),
        migrations.AddIndex(
            model_name='xrayimage',
            index=models.Index(fields=['user', '-upload_time'], name='model_servi_user_id_4ff343_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user', '-timestamp'], name='model_servi_user_id_d82891_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['action_type'], name='model_servi_action__ce9a89_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['image', '-created_at'], name='model_servi_image_i_2f260e_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['prediction_label'], name='model_servi_predict_c9f949_idx'),
        ),
    ]
